services:
  mysql:
    image: mysql:8.0
    container_name: report_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: report_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: report-backend
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=report_db
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app # This mounts your application code for live development
    command: npm run dev

volumes:
  mysql_data:
