openapi: 3.0.0
info:
  title: Silo Report API
  description: API for generating silo data reports synchronously
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: https://api.example.com/api
    description: Production server

paths:
  /initiate-silo-report:
    post:
      summary: Generate a silo report
      description: |
        Generates a comprehensive Excel report containing silo data analysis with multiple sheets:
        - Dashboard: Overview of key metrics and statistics
        - Summary Statistics: Detailed statistics for each silo
        - Detailed Data: Raw data with hourly aggregations
      operationId: generateReport
      tags:
        - Reports
      responses:
        "200":
          description: Report generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                    description: Unique identifier for the report generation job
                    example: "report-2024-03-21-123456"
                  status:
                    type: string
                    description: Current status of the report generation
                    enum: [COMPLETED, PROCESSING, FAILED]
                    example: "COMPLETED"
                  s3Url:
                    type: string
                    format: uri
                    description: Pre-signed S3 URL for downloading the report (valid for 1 hour)
                    example: "https://example-bucket.s3.amazonaws.com/report-2024-03-21.xlsx"
                  itemsProcessed:
                    type: integer
                    description: Number of data records processed in the report
                    example: 1200
                required:
                  - jobId
                  - status
                  - s3Url
                  - itemsProcessed
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        message:
          type: string
          description: Detailed error message (only in development environment)
          nullable: true
      required:
        - error
