openapi: 3.0.0
info:
  title: Silo Report API
  description: API for generating silo data reports synchronously
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: https://api.example.com/api
    description: Production server

paths:
  /initiate-silo-report:
    post:
      summary: Generate a silo report
      description: Generates a report synchronously and returns the S3 URL for downloading
      operationId: generateReport
      tags:
        - Reports
      responses:
        "200":
          description: Report generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  s3Url:
                    type: string
                    format: uri
                    description: Pre-signed S3 URL for downloading the report
                    example: "https://example-bucket.s3.amazonaws.com/report-2024-03-21.xlsx"
                  errorMessage:
                    type: string
                    description: Error message if the report generation failed
                    nullable: true
                required:
                  - s3Url
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        message:
          type: string
          description: Detailed error message (only in development environment)
          nullable: true
      required:
        - error
